development:
  cloud_name: xxx
  api_key: 'xxx'
  api_secret: xxx
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: xxx
  api_key: 'xxx'
  api_secret: xxx
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: xxx
  api_key: 'xxx'
  api_secret: xxx
  enhance_image_tag: true
  static_file_support: false
